language: python
python: 
 - "3.6.6"
env:
 - DJANGO=2.0 DB=postgres
global:
 - PGPORT=5432
install:
 - pip install -r requirements.txt
sudo: required
services:
 - docker
script:
 - sonar-scanner
 - docker exec -ti decide_web ./manage.py test
addons:
  postgresql: "9.6"
  sonarcloud:
    organization: "pablotabares-github"
before_script:
 - cd decide
 - cp local_settings.example.py local_settings.py
 - psql -c "create user decide with password 'decide'"
 - psql -c "create database decide owner decide"
 - python ./manage.py migrate
 - cd ..
notifications:
  email: false
before_install:
 - docker-compose up -d
deploy:
  provider: heroku
  api_key:
    secure: "12d10fb9-7aba-4270-97a8-9058515b8887"
  app: decide-ortosia
  on:
    all_branches: true
  skip_cleanup: true
